/**
 * Represents a brand entity with key performance indicators.
 */
export type Brand = {
  /** URL or path to the brand's logo image */
  logo: string;
  
  /** Name of the brand */
  name: string;
  
  /** Number of unique visitors to the brand's website or store */
  visitors: number;
  
  /** Total revenue generated by the brand (formatted as a string, e.g., "$1,000,000") */
  revenue: string;
  
  /** Number of completed sales or transactions */
  sales: number;
  
  /** Conversion rate as a decimal (e.g., 0.05 for 5%) */
  conversionRate: number;
};
