/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

// Import the anyApi function from the Convex server package
import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */

// Export the api object, which is an instance of anyApi
// This allows you to reference your Convex functions throughout your app
export const api = anyApi;

// Export the internal object, which is also an instance of anyApi
// This is typically used for internal Convex functions not exposed to the client
export const internal = anyApi;

// Note: This file is automatically generated and should not be manually edited.
// If you need to update the API, make changes to your Convex functions and run `npx convex dev`.
